### ISSUE TITLE
Design new Swag for Giveth with new branding

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-design-assets#5]
Start with T-shirt designs. Use new branding and graphic assets but don't stop there, be creative and extend the brand with new graphics as you see fit. Make something unique for Giveth. 

Example Gitcoin swag 
https://store.gitcoin.co/collections/homepage-2021/products/quadratic-lands-t-shirt
https://store.gitcoin.co/products/2019-ethereal-gitcoin-cellarius-ladies-short-sleeve-t-shirt
https://store.gitcoin.co/products/decentralized

More https://store.gitcoin.co/collections/all

@rodricastillo9013

**Comment by markoprljic** [comment]
@Danibelle Please forward print shop spec if you have any.

**Comment by Danibelle** [comment]
Notice every sticker and "schwag pack" is sold out!!

Let's design some rad stickers .. they are so 🔥

**Comment by Danibelle** [comment]
here are the sticker specs - https://www.stickermule.com/support/artwork
transfer stickers: https://www.stickermule.com/support/how-do-i-design-a-transfer-sticker

Desperately seeking vector art files..  I don't know what I'm looking for though or where... 🆘 

This is what they tell me for the shirts: The best Digital Files for submission for Screen Printing or Embroidery are Vector Art Files such as Adobe Illustrator, Indesign, PDF, EPS, etc. With Vector Art your able to go from a Business Card to a Billboard with out losing quality. Denver T-Shirt can help create artwork for your project and in most cases, we can convert high quality Raster Files to Vector Art.

**due to turnaround time it's best we give them the vector art**

@markoprljic @rodricastillo9013

**Comment by Danibelle** [comment]
Thanks everyone for your participation in the creation of epic Giveth Swag!
